<?xml version="1.0"?>
<mujoco model="floating_manipulator" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <option gravity="0 0 0" timestep="0.01" />
    <visual>
        <global offwidth="1920" offheight="1080" />
        <rgba haze="0.1 0.1 0.2 1" />
    </visual>


    <worldbody>
        <camera name="overview" pos="80 0 0" xyaxes="0 1 0 0 0 1" />
        <light pos="0 0 100" dir="0 0 -1" diffuse="0.8 0.8 0.8" />
        <light pos="100 100 100" dir="-1 -1 -1" diffuse="0.5 0.5 0.5" />

        <body name="adeos2" pos="0 80 0">
            <!-- 
                ADEOS II (Midori II) 4x4x6[m] 3.7[t] https://www.jaxa.jp/projects/sat/adeos2/index_j.html
                太陽電池171kg 2.6x26[m] 171[kg]  https://doi.org/10.1109/PVSC.1996.564010
                ADEOS1 燃料135kg? http://www.astronautix.com/a/adeos.html
            -->

            <!-- properties -->
            <xacro:property name="adeos2_base_size_x" value="6" />
            <xacro:property name="adeos2_base_size_y" value="4" />
            <xacro:property name="adeos2_base_size_z" value="4" />
            <xacro:property name="adeos2_solar_size_x" value="0.20" />
            <xacro:property name="adeos2_solar_size_y" value="26" />
            <xacro:property name="adeos2_solar_size_z" value="2.6" />
            <freejoint />
            <!-- Main satellite body -->
            <body name="base" pos="0 0 0">
                <geom type="box"
                    size="${adeos2_base_size_x/2} ${adeos2_base_size_y/2} ${adeos2_base_size_z/2}"
                    rgba="0.7 0.7 0.7 1" mass="3529" />
            </body>
            <!-- Single large solar array paddle -->
            <body name="solar_array" pos="2 ${(adeos2_base_size_y + adeos2_solar_size_y)/2} 0">
                <!-- 適当な偏心 -->
                <geom type="box"
                    size="${adeos2_solar_size_x/2} ${adeos2_solar_size_y/2} ${adeos2_solar_size_z/2}"
                    rgba="0.1 0.1 0.5 1" mass="171" />
            </body>
        </body>
    </worldbody>

    <keyframe>
        <key name="stationary" qpos="0 0 0 1 0 0 0" qvel="0 0 0 0 0 0" />
    </keyframe>
</mujoco>